import json
import os
import pathlib
import re
import sys

import yaml


DESCRIPTION_LIMIT = 100
HEX_COLOR = re.compile(r"^[0-9A-Fa-f]{6}$")

CLASSIFICATION_COLOR = "1D76DB"
REVIEW_COLOR = "FBCA04"
REPORTING_COLOR = "0E8A16"

REVIEW_DESCRIPTIONS = {
    "ai-triage:needs-review": "Needs human review before the workflow takes further action.",
    "ai-triage:accepted": "A human reviewed and accepted the AI triage result.",
    "ai-triage:corrected": "A human reviewed and corrected the AI triage result.",
    "ai-triage:bad-label": "Marks an issue where the AI triage workflow applied the wrong label.",
    "ai-triage:bad-comment": "Marks an issue where the AI triage workflow suggested a bad comment.",
    "ai-triage:done": "Marks an issue whose AI triage workflow is complete.",
}

REPORTING_DESCRIPTIONS = {
    "ai-triage:report": "Marks a workflow-created report issue that summarizes broader triage findings.",
    "ai-generated-issue": "Indicates that the issue body was generated by automation.",
}


def fail(message):
    sys.exit(message)


def trim_description(text):
    text = " ".join(str(text or "").split())
    if not text:
        return "Managed by the Team Issue Triage workflow."
    if len(text) <= DESCRIPTION_LIMIT:
        return text

    trimmed = text[: DESCRIPTION_LIMIT - 3].rstrip()
    return f"{trimmed}..."


def normalize_color(value, *, default):
    """Validate ``value`` (or ``default`` when missing) as a 6-char hex color."""
    raw = value if value not in (None, "") else default
    if raw in (None, ""):
        fail("Label color is required and no default was supplied.")
    color = str(raw).strip()
    if not HEX_COLOR.match(color):
        fail(f"Label color must be a 6-character hex value: {color!r}")
    return color.upper()


def append_output(values):
    output_path = os.environ.get("GITHUB_OUTPUT")
    if not output_path:
        return

    with pathlib.Path(output_path).open("a") as output:
        for name, value in values.items():
            output.write(f"{name}={value}\n")


def main():
    labels_path = pathlib.Path(os.environ["TRIAGE_LABELS"])
    labels_cfg = yaml.safe_load(labels_path.read_text()) or {}

    specs = []
    seen = set()

    def add_spec(name, color, description, *, default_color):
        label = {
            "name": str(name or "").strip(),
            "color": normalize_color(color, default=default_color),
            "description": trim_description(description),
        }
        if not label["name"]:
            fail(f"{labels_path}: label name cannot be empty.")
        if label["name"] in seen:
            fail(f"{labels_path}: duplicate managed label entry: {label['name']}")
        seen.add(label["name"])
        specs.append(label)

    for entry in labels_cfg.get("classification") or []:
        add_spec(
            entry.get("name"),
            entry.get("color") or CLASSIFICATION_COLOR,
            entry.get("description") or entry.get("requirement"),
            default_color=CLASSIFICATION_COLOR,
        )

    for entry in labels_cfg.get("priority") or []:
        add_spec(
            entry.get("name"),
            entry.get("color"),
            entry.get("description") or entry.get("meaning"),
            default_color=None,
        )

    for entry in labels_cfg.get("review") or []:
        if isinstance(entry, dict):
            add_spec(
                entry.get("name"),
                entry.get("color") or REVIEW_COLOR,
                entry.get("description") or REVIEW_DESCRIPTIONS.get(str(entry.get("name")).strip()),
                default_color=REVIEW_COLOR,
            )
        else:
            add_spec(
                entry,
                REVIEW_COLOR,
                REVIEW_DESCRIPTIONS.get(str(entry).strip()),
                default_color=REVIEW_COLOR,
            )

    for entry in labels_cfg.get("reporting") or []:
        if isinstance(entry, dict):
            add_spec(
                entry.get("name"),
                entry.get("color") or REPORTING_COLOR,
                entry.get("description") or REPORTING_DESCRIPTIONS.get(str(entry.get("name")).strip()),
                default_color=REPORTING_COLOR,
            )
        else:
            add_spec(
                entry,
                REPORTING_COLOR,
                REPORTING_DESCRIPTIONS.get(str(entry).strip()),
                default_color=REPORTING_COLOR,
            )

    allowed = {str(label).strip() for label in (labels_cfg.get("allowed_safe_output_labels") or [])}
    missing = sorted(label for label in allowed if label not in seen)
    if missing:
        fail(
            f"{labels_path}: allowed_safe_output_labels includes labels without managed specs: {missing}"
        )

    specs_json = json.dumps(specs, separators=(",", ":"))
    allowed_csv = ",".join(sorted(allowed))
    append_output(
        {
            "label_specs_json": specs_json,
            "label_count": str(len(specs)),
            "allowed_labels": allowed_csv,
            "allowed_label_count": str(len(allowed)),
        }
    )
    print(specs_json)


if __name__ == "__main__":
    main()
